### ISSUE TITLE
keep same id when restarting

### ISSUE THREAD

**Issue by annecori** [annecori/TypoChallenge#32]
At the moment when someone restarts the challenge from the button on the end page, they have to take the survey again, and this gets allocated a new ID. I think we know this is the same person so would like to skip the survey and record the same ID if possible?

**Comment by richfitz** [comment]
Can you check the logic as of 8623569?

**Comment by annecori** [comment]
Thanks @rich, so
- I like the continue button and actually suggests it comes first (i.e. to the left of the "restart the challenge"
- from the user perspective, I see the point of "restarting" to get better stats, but I still think it's annoying to have to take the survey again, and for us I think it's annoying to have another session ID. 

My suggestion would be to have 3 buttons (in that order I think): 
- Continue challenge --> as it is now
- Restart challenge (same user) --> would take you straight to the instruction page so skip the survey and keep the ID and survey results from last time
- Restart challenge (new user) --> would be what the Restart challenge button is currently

Does that make sense?

**Comment by richfitz** [comment]
OK, that's done as of 7ed9dcd - can you take a look?

**Comment by annecori** [comment]
on new user reset id_parent = NULL

**Comment by richfitz** [comment]
ok, ready for another check
