### ISSUE TITLE
warnings need to me removed

### ISSUE THREAD

**Issue by annecori** [annecori/TypoChallenge#36]
Saving data for '5f0fd048-35bd-41c9-a72a-19ed4b9dd18a'
Warning in mean.default(s[, "total"]) :
  argument is not numeric or logical: returning NA
Warning in mean.default(s[, "correct"]) :
  argument is not numeric or logical: returning NA
Warning in max(s[, "total"]) :
  no non-missing arguments to max; returning -Inf
Warning in read_contributions() :
  NAs introduced by coercion to integer range
Warning in max(s[, "correct"]) :
  no non-missing arguments to max; returning -Inf
Warning in read_contributions() :
  NAs introduced by coercion to integer range
Warning in min(s[, "best"]) :
  no non-missing arguments to min; returning Inf
Warning in mean.default(s[, "best"]) :
  argument is not numeric or logical: returning NA
Warning in min(s[, "mean"]) :
  no non-missing arguments to min; returning Inf
Warning in mean.default(s[, "mean"]) :
  argument is not numeric or logical: returning NA

**Comment by richfitz** [comment]
I can't replicate this locally :(

**Comment by annecori** [comment]
me neither...

**Comment by richfitz** [comment]
nm, got it in 47d65eb8ddee6312f24010e31f2e230126035789
