### ISSUE TITLE
repeat personal and global stats on the end page

### ISSUE THREAD

**Issue by annecori** [annecori/TypoChallenge#43]
would be nice if we could do that, 
then I would also be able to add things like ranking based on speed or number of entries etc once the person is on the end page

**Comment by richfitz** [comment]
done as of 4b15762 - please check

**Comment by richfitz** [comment]
Also note that now there is a `DEVEL_VERSION` flag that you can use to change behaviour in testing (and a cheat button)

**Comment by annecori** [comment]
is it easy to make the left panel a bit wider?
